run:
  skip-dirs-use-default: false

linters:
  enable-all: true
  disable:
    - tagalign
    - ireturn
    - gofumpt
    - testpackage
    - funlen
    - goerr113
    - gomnd
    - errchkjson
    - cyclop
    - stylecheck
    - depguard
    - nlreturn
    - forcetypeassert
    - exhaustruct
    - varnamelen
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag

    # Deprecated ones:
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

gocyclo:
  min-complexity: 15

issues:
  exclude-use-default: false
  exclude-rules:
    - path: "status_code_test\\.go$"
      linters:
        - staticcheck
    - path: "lib/examples/.+\\.go$"
      linters:
        - revive
    - path: ".+\\_test.go$"
      linters:
        - revive
