// Code generated by "enumer -type=StatusCode -values -trimprefix=Status"; DO NOT EDIT.

package openapi

import (
	"fmt"
	"strings"
)

const _StatusCodeName = "ContinueSwitchingProtocolsProcessingEarlyHintsOKCreatedAcceptedNonAuthoritativeInfoNoContentResetContentPartialContentMultiStatusAlreadyReportedIMUsedMultipleChoicesMovedPermanentlyFoundSeeOtherNotModifiedUseProxyTemporaryRedirectPermanentRedirectBadRequestUnauthorizedPaymentRequiredForbiddenNotFoundMethodNotAllowedNotAcceptableProxyAuthRequiredRequestTimeoutConflictGoneLengthRequiredPreconditionFailedRequestEntityTooLargeRequestURITooLongUnsupportedMediaTypeRequestedRangeNotSatisfiableExpectationFailedTeapotMisdirectedRequestUnprocessableEntityLockedFailedDependencyTooEarlyUpgradeRequiredPreconditionRequiredTooManyRequestsRequestHeaderFieldsTooLargeUnavailableForLegalReasonsInternalServerErrorNotImplementedBadGatewayServiceUnavailableGatewayTimeoutHTTPVersionNotSupportedVariantAlsoNegotiatesInsufficientStorageLoopDetectedNotExtendedNetworkAuthenticationRequired"
const _StatusCodeLowerName = "continueswitchingprotocolsprocessingearlyhintsokcreatedacceptednonauthoritativeinfonocontentresetcontentpartialcontentmultistatusalreadyreportedimusedmultiplechoicesmovedpermanentlyfoundseeothernotmodifieduseproxytemporaryredirectpermanentredirectbadrequestunauthorizedpaymentrequiredforbiddennotfoundmethodnotallowednotacceptableproxyauthrequiredrequesttimeoutconflictgonelengthrequiredpreconditionfailedrequestentitytoolargerequesturitoolongunsupportedmediatyperequestedrangenotsatisfiableexpectationfailedteapotmisdirectedrequestunprocessableentitylockedfaileddependencytooearlyupgraderequiredpreconditionrequiredtoomanyrequestsrequestheaderfieldstoolargeunavailableforlegalreasonsinternalservererrornotimplementedbadgatewayserviceunavailablegatewaytimeouthttpversionnotsupportedvariantalsonegotiatesinsufficientstorageloopdetectednotextendednetworkauthenticationrequired"

var _StatusCodeMap = map[StatusCode]string{
	100: _StatusCodeName[0:8],
	101: _StatusCodeName[8:26],
	102: _StatusCodeName[26:36],
	103: _StatusCodeName[36:46],
	200: _StatusCodeName[46:48],
	201: _StatusCodeName[48:55],
	202: _StatusCodeName[55:63],
	203: _StatusCodeName[63:83],
	204: _StatusCodeName[83:92],
	205: _StatusCodeName[92:104],
	206: _StatusCodeName[104:118],
	207: _StatusCodeName[118:129],
	208: _StatusCodeName[129:144],
	226: _StatusCodeName[144:150],
	300: _StatusCodeName[150:165],
	301: _StatusCodeName[165:181],
	302: _StatusCodeName[181:186],
	303: _StatusCodeName[186:194],
	304: _StatusCodeName[194:205],
	305: _StatusCodeName[205:213],
	307: _StatusCodeName[213:230],
	308: _StatusCodeName[230:247],
	400: _StatusCodeName[247:257],
	401: _StatusCodeName[257:269],
	402: _StatusCodeName[269:284],
	403: _StatusCodeName[284:293],
	404: _StatusCodeName[293:301],
	405: _StatusCodeName[301:317],
	406: _StatusCodeName[317:330],
	407: _StatusCodeName[330:347],
	408: _StatusCodeName[347:361],
	409: _StatusCodeName[361:369],
	410: _StatusCodeName[369:373],
	411: _StatusCodeName[373:387],
	412: _StatusCodeName[387:405],
	413: _StatusCodeName[405:426],
	414: _StatusCodeName[426:443],
	415: _StatusCodeName[443:463],
	416: _StatusCodeName[463:491],
	417: _StatusCodeName[491:508],
	418: _StatusCodeName[508:514],
	421: _StatusCodeName[514:532],
	422: _StatusCodeName[532:551],
	423: _StatusCodeName[551:557],
	424: _StatusCodeName[557:573],
	425: _StatusCodeName[573:581],
	426: _StatusCodeName[581:596],
	428: _StatusCodeName[596:616],
	429: _StatusCodeName[616:631],
	431: _StatusCodeName[631:658],
	451: _StatusCodeName[658:684],
	500: _StatusCodeName[684:703],
	501: _StatusCodeName[703:717],
	502: _StatusCodeName[717:727],
	503: _StatusCodeName[727:745],
	504: _StatusCodeName[745:759],
	505: _StatusCodeName[759:782],
	506: _StatusCodeName[782:803],
	507: _StatusCodeName[803:822],
	508: _StatusCodeName[822:834],
	510: _StatusCodeName[834:845],
	511: _StatusCodeName[845:874],
}

func (i StatusCode) String() string {
	if str, ok := _StatusCodeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("StatusCode(%d)", i)
}

func (StatusCode) Values() []string {
	return StatusCodeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusCodeNoOp() {
	var x [1]struct{}
	_ = x[StatusContinue-(100)]
	_ = x[StatusSwitchingProtocols-(101)]
	_ = x[StatusProcessing-(102)]
	_ = x[StatusEarlyHints-(103)]
	_ = x[StatusOK-(200)]
	_ = x[StatusCreated-(201)]
	_ = x[StatusAccepted-(202)]
	_ = x[StatusNonAuthoritativeInfo-(203)]
	_ = x[StatusNoContent-(204)]
	_ = x[StatusResetContent-(205)]
	_ = x[StatusPartialContent-(206)]
	_ = x[StatusMultiStatus-(207)]
	_ = x[StatusAlreadyReported-(208)]
	_ = x[StatusIMUsed-(226)]
	_ = x[StatusMultipleChoices-(300)]
	_ = x[StatusMovedPermanently-(301)]
	_ = x[StatusFound-(302)]
	_ = x[StatusSeeOther-(303)]
	_ = x[StatusNotModified-(304)]
	_ = x[StatusUseProxy-(305)]
	_ = x[StatusTemporaryRedirect-(307)]
	_ = x[StatusPermanentRedirect-(308)]
	_ = x[StatusBadRequest-(400)]
	_ = x[StatusUnauthorized-(401)]
	_ = x[StatusPaymentRequired-(402)]
	_ = x[StatusForbidden-(403)]
	_ = x[StatusNotFound-(404)]
	_ = x[StatusMethodNotAllowed-(405)]
	_ = x[StatusNotAcceptable-(406)]
	_ = x[StatusProxyAuthRequired-(407)]
	_ = x[StatusRequestTimeout-(408)]
	_ = x[StatusConflict-(409)]
	_ = x[StatusGone-(410)]
	_ = x[StatusLengthRequired-(411)]
	_ = x[StatusPreconditionFailed-(412)]
	_ = x[StatusRequestEntityTooLarge-(413)]
	_ = x[StatusRequestURITooLong-(414)]
	_ = x[StatusUnsupportedMediaType-(415)]
	_ = x[StatusRequestedRangeNotSatisfiable-(416)]
	_ = x[StatusExpectationFailed-(417)]
	_ = x[StatusTeapot-(418)]
	_ = x[StatusMisdirectedRequest-(421)]
	_ = x[StatusUnprocessableEntity-(422)]
	_ = x[StatusLocked-(423)]
	_ = x[StatusFailedDependency-(424)]
	_ = x[StatusTooEarly-(425)]
	_ = x[StatusUpgradeRequired-(426)]
	_ = x[StatusPreconditionRequired-(428)]
	_ = x[StatusTooManyRequests-(429)]
	_ = x[StatusRequestHeaderFieldsTooLarge-(431)]
	_ = x[StatusUnavailableForLegalReasons-(451)]
	_ = x[StatusInternalServerError-(500)]
	_ = x[StatusNotImplemented-(501)]
	_ = x[StatusBadGateway-(502)]
	_ = x[StatusServiceUnavailable-(503)]
	_ = x[StatusGatewayTimeout-(504)]
	_ = x[StatusHTTPVersionNotSupported-(505)]
	_ = x[StatusVariantAlsoNegotiates-(506)]
	_ = x[StatusInsufficientStorage-(507)]
	_ = x[StatusLoopDetected-(508)]
	_ = x[StatusNotExtended-(510)]
	_ = x[StatusNetworkAuthenticationRequired-(511)]
}

var _StatusCodeValues = []StatusCode{StatusContinue, StatusSwitchingProtocols, StatusProcessing, StatusEarlyHints, StatusOK, StatusCreated, StatusAccepted, StatusNonAuthoritativeInfo, StatusNoContent, StatusResetContent, StatusPartialContent, StatusMultiStatus, StatusAlreadyReported, StatusIMUsed, StatusMultipleChoices, StatusMovedPermanently, StatusFound, StatusSeeOther, StatusNotModified, StatusUseProxy, StatusTemporaryRedirect, StatusPermanentRedirect, StatusBadRequest, StatusUnauthorized, StatusPaymentRequired, StatusForbidden, StatusNotFound, StatusMethodNotAllowed, StatusNotAcceptable, StatusProxyAuthRequired, StatusRequestTimeout, StatusConflict, StatusGone, StatusLengthRequired, StatusPreconditionFailed, StatusRequestEntityTooLarge, StatusRequestURITooLong, StatusUnsupportedMediaType, StatusRequestedRangeNotSatisfiable, StatusExpectationFailed, StatusTeapot, StatusMisdirectedRequest, StatusUnprocessableEntity, StatusLocked, StatusFailedDependency, StatusTooEarly, StatusUpgradeRequired, StatusPreconditionRequired, StatusTooManyRequests, StatusRequestHeaderFieldsTooLarge, StatusUnavailableForLegalReasons, StatusInternalServerError, StatusNotImplemented, StatusBadGateway, StatusServiceUnavailable, StatusGatewayTimeout, StatusHTTPVersionNotSupported, StatusVariantAlsoNegotiates, StatusInsufficientStorage, StatusLoopDetected, StatusNotExtended, StatusNetworkAuthenticationRequired}

var _StatusCodeNameToValueMap = map[string]StatusCode{
	_StatusCodeName[0:8]:          StatusContinue,
	_StatusCodeLowerName[0:8]:     StatusContinue,
	_StatusCodeName[8:26]:         StatusSwitchingProtocols,
	_StatusCodeLowerName[8:26]:    StatusSwitchingProtocols,
	_StatusCodeName[26:36]:        StatusProcessing,
	_StatusCodeLowerName[26:36]:   StatusProcessing,
	_StatusCodeName[36:46]:        StatusEarlyHints,
	_StatusCodeLowerName[36:46]:   StatusEarlyHints,
	_StatusCodeName[46:48]:        StatusOK,
	_StatusCodeLowerName[46:48]:   StatusOK,
	_StatusCodeName[48:55]:        StatusCreated,
	_StatusCodeLowerName[48:55]:   StatusCreated,
	_StatusCodeName[55:63]:        StatusAccepted,
	_StatusCodeLowerName[55:63]:   StatusAccepted,
	_StatusCodeName[63:83]:        StatusNonAuthoritativeInfo,
	_StatusCodeLowerName[63:83]:   StatusNonAuthoritativeInfo,
	_StatusCodeName[83:92]:        StatusNoContent,
	_StatusCodeLowerName[83:92]:   StatusNoContent,
	_StatusCodeName[92:104]:       StatusResetContent,
	_StatusCodeLowerName[92:104]:  StatusResetContent,
	_StatusCodeName[104:118]:      StatusPartialContent,
	_StatusCodeLowerName[104:118]: StatusPartialContent,
	_StatusCodeName[118:129]:      StatusMultiStatus,
	_StatusCodeLowerName[118:129]: StatusMultiStatus,
	_StatusCodeName[129:144]:      StatusAlreadyReported,
	_StatusCodeLowerName[129:144]: StatusAlreadyReported,
	_StatusCodeName[144:150]:      StatusIMUsed,
	_StatusCodeLowerName[144:150]: StatusIMUsed,
	_StatusCodeName[150:165]:      StatusMultipleChoices,
	_StatusCodeLowerName[150:165]: StatusMultipleChoices,
	_StatusCodeName[165:181]:      StatusMovedPermanently,
	_StatusCodeLowerName[165:181]: StatusMovedPermanently,
	_StatusCodeName[181:186]:      StatusFound,
	_StatusCodeLowerName[181:186]: StatusFound,
	_StatusCodeName[186:194]:      StatusSeeOther,
	_StatusCodeLowerName[186:194]: StatusSeeOther,
	_StatusCodeName[194:205]:      StatusNotModified,
	_StatusCodeLowerName[194:205]: StatusNotModified,
	_StatusCodeName[205:213]:      StatusUseProxy,
	_StatusCodeLowerName[205:213]: StatusUseProxy,
	_StatusCodeName[213:230]:      StatusTemporaryRedirect,
	_StatusCodeLowerName[213:230]: StatusTemporaryRedirect,
	_StatusCodeName[230:247]:      StatusPermanentRedirect,
	_StatusCodeLowerName[230:247]: StatusPermanentRedirect,
	_StatusCodeName[247:257]:      StatusBadRequest,
	_StatusCodeLowerName[247:257]: StatusBadRequest,
	_StatusCodeName[257:269]:      StatusUnauthorized,
	_StatusCodeLowerName[257:269]: StatusUnauthorized,
	_StatusCodeName[269:284]:      StatusPaymentRequired,
	_StatusCodeLowerName[269:284]: StatusPaymentRequired,
	_StatusCodeName[284:293]:      StatusForbidden,
	_StatusCodeLowerName[284:293]: StatusForbidden,
	_StatusCodeName[293:301]:      StatusNotFound,
	_StatusCodeLowerName[293:301]: StatusNotFound,
	_StatusCodeName[301:317]:      StatusMethodNotAllowed,
	_StatusCodeLowerName[301:317]: StatusMethodNotAllowed,
	_StatusCodeName[317:330]:      StatusNotAcceptable,
	_StatusCodeLowerName[317:330]: StatusNotAcceptable,
	_StatusCodeName[330:347]:      StatusProxyAuthRequired,
	_StatusCodeLowerName[330:347]: StatusProxyAuthRequired,
	_StatusCodeName[347:361]:      StatusRequestTimeout,
	_StatusCodeLowerName[347:361]: StatusRequestTimeout,
	_StatusCodeName[361:369]:      StatusConflict,
	_StatusCodeLowerName[361:369]: StatusConflict,
	_StatusCodeName[369:373]:      StatusGone,
	_StatusCodeLowerName[369:373]: StatusGone,
	_StatusCodeName[373:387]:      StatusLengthRequired,
	_StatusCodeLowerName[373:387]: StatusLengthRequired,
	_StatusCodeName[387:405]:      StatusPreconditionFailed,
	_StatusCodeLowerName[387:405]: StatusPreconditionFailed,
	_StatusCodeName[405:426]:      StatusRequestEntityTooLarge,
	_StatusCodeLowerName[405:426]: StatusRequestEntityTooLarge,
	_StatusCodeName[426:443]:      StatusRequestURITooLong,
	_StatusCodeLowerName[426:443]: StatusRequestURITooLong,
	_StatusCodeName[443:463]:      StatusUnsupportedMediaType,
	_StatusCodeLowerName[443:463]: StatusUnsupportedMediaType,
	_StatusCodeName[463:491]:      StatusRequestedRangeNotSatisfiable,
	_StatusCodeLowerName[463:491]: StatusRequestedRangeNotSatisfiable,
	_StatusCodeName[491:508]:      StatusExpectationFailed,
	_StatusCodeLowerName[491:508]: StatusExpectationFailed,
	_StatusCodeName[508:514]:      StatusTeapot,
	_StatusCodeLowerName[508:514]: StatusTeapot,
	_StatusCodeName[514:532]:      StatusMisdirectedRequest,
	_StatusCodeLowerName[514:532]: StatusMisdirectedRequest,
	_StatusCodeName[532:551]:      StatusUnprocessableEntity,
	_StatusCodeLowerName[532:551]: StatusUnprocessableEntity,
	_StatusCodeName[551:557]:      StatusLocked,
	_StatusCodeLowerName[551:557]: StatusLocked,
	_StatusCodeName[557:573]:      StatusFailedDependency,
	_StatusCodeLowerName[557:573]: StatusFailedDependency,
	_StatusCodeName[573:581]:      StatusTooEarly,
	_StatusCodeLowerName[573:581]: StatusTooEarly,
	_StatusCodeName[581:596]:      StatusUpgradeRequired,
	_StatusCodeLowerName[581:596]: StatusUpgradeRequired,
	_StatusCodeName[596:616]:      StatusPreconditionRequired,
	_StatusCodeLowerName[596:616]: StatusPreconditionRequired,
	_StatusCodeName[616:631]:      StatusTooManyRequests,
	_StatusCodeLowerName[616:631]: StatusTooManyRequests,
	_StatusCodeName[631:658]:      StatusRequestHeaderFieldsTooLarge,
	_StatusCodeLowerName[631:658]: StatusRequestHeaderFieldsTooLarge,
	_StatusCodeName[658:684]:      StatusUnavailableForLegalReasons,
	_StatusCodeLowerName[658:684]: StatusUnavailableForLegalReasons,
	_StatusCodeName[684:703]:      StatusInternalServerError,
	_StatusCodeLowerName[684:703]: StatusInternalServerError,
	_StatusCodeName[703:717]:      StatusNotImplemented,
	_StatusCodeLowerName[703:717]: StatusNotImplemented,
	_StatusCodeName[717:727]:      StatusBadGateway,
	_StatusCodeLowerName[717:727]: StatusBadGateway,
	_StatusCodeName[727:745]:      StatusServiceUnavailable,
	_StatusCodeLowerName[727:745]: StatusServiceUnavailable,
	_StatusCodeName[745:759]:      StatusGatewayTimeout,
	_StatusCodeLowerName[745:759]: StatusGatewayTimeout,
	_StatusCodeName[759:782]:      StatusHTTPVersionNotSupported,
	_StatusCodeLowerName[759:782]: StatusHTTPVersionNotSupported,
	_StatusCodeName[782:803]:      StatusVariantAlsoNegotiates,
	_StatusCodeLowerName[782:803]: StatusVariantAlsoNegotiates,
	_StatusCodeName[803:822]:      StatusInsufficientStorage,
	_StatusCodeLowerName[803:822]: StatusInsufficientStorage,
	_StatusCodeName[822:834]:      StatusLoopDetected,
	_StatusCodeLowerName[822:834]: StatusLoopDetected,
	_StatusCodeName[834:845]:      StatusNotExtended,
	_StatusCodeLowerName[834:845]: StatusNotExtended,
	_StatusCodeName[845:874]:      StatusNetworkAuthenticationRequired,
	_StatusCodeLowerName[845:874]: StatusNetworkAuthenticationRequired,
}

var _StatusCodeNames = []string{
	_StatusCodeName[0:8],
	_StatusCodeName[8:26],
	_StatusCodeName[26:36],
	_StatusCodeName[36:46],
	_StatusCodeName[46:48],
	_StatusCodeName[48:55],
	_StatusCodeName[55:63],
	_StatusCodeName[63:83],
	_StatusCodeName[83:92],
	_StatusCodeName[92:104],
	_StatusCodeName[104:118],
	_StatusCodeName[118:129],
	_StatusCodeName[129:144],
	_StatusCodeName[144:150],
	_StatusCodeName[150:165],
	_StatusCodeName[165:181],
	_StatusCodeName[181:186],
	_StatusCodeName[186:194],
	_StatusCodeName[194:205],
	_StatusCodeName[205:213],
	_StatusCodeName[213:230],
	_StatusCodeName[230:247],
	_StatusCodeName[247:257],
	_StatusCodeName[257:269],
	_StatusCodeName[269:284],
	_StatusCodeName[284:293],
	_StatusCodeName[293:301],
	_StatusCodeName[301:317],
	_StatusCodeName[317:330],
	_StatusCodeName[330:347],
	_StatusCodeName[347:361],
	_StatusCodeName[361:369],
	_StatusCodeName[369:373],
	_StatusCodeName[373:387],
	_StatusCodeName[387:405],
	_StatusCodeName[405:426],
	_StatusCodeName[426:443],
	_StatusCodeName[443:463],
	_StatusCodeName[463:491],
	_StatusCodeName[491:508],
	_StatusCodeName[508:514],
	_StatusCodeName[514:532],
	_StatusCodeName[532:551],
	_StatusCodeName[551:557],
	_StatusCodeName[557:573],
	_StatusCodeName[573:581],
	_StatusCodeName[581:596],
	_StatusCodeName[596:616],
	_StatusCodeName[616:631],
	_StatusCodeName[631:658],
	_StatusCodeName[658:684],
	_StatusCodeName[684:703],
	_StatusCodeName[703:717],
	_StatusCodeName[717:727],
	_StatusCodeName[727:745],
	_StatusCodeName[745:759],
	_StatusCodeName[759:782],
	_StatusCodeName[782:803],
	_StatusCodeName[803:822],
	_StatusCodeName[822:834],
	_StatusCodeName[834:845],
	_StatusCodeName[845:874],
}

// StatusCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusCodeString(s string) (StatusCode, error) {
	if val, ok := _StatusCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StatusCode values", s)
}

// StatusCodeValues returns all values of the enum
func StatusCodeValues() []StatusCode {
	return _StatusCodeValues
}

// StatusCodeStrings returns a slice of all String values of the enum
func StatusCodeStrings() []string {
	strs := make([]string, len(_StatusCodeNames))
	copy(strs, _StatusCodeNames)
	return strs
}

// IsAStatusCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StatusCode) IsAStatusCode() bool {
	_, ok := _StatusCodeMap[i]
	return ok
}
