name: Go
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - uses: actions/checkout@v3

      - name: generate code
        run: go generate ./...

      - name: lint
        run: go run github.com/ysmood/golangci-lint@latest

      - name: test
        run: go test -coverprofile=coverage.out ./...

      - name: coverage
        run: go run github.com/ysmood/got/cmd/check-cov@latest
